/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewaoutdoor;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Taufik Yahya
 */
public class Sewa extends javax.swing.JFrame {

    /**
     * Creates new form Sewa
     */
    public Sewa() {
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(new java.awt.Color(0,0,0,0));
    }
    
    private int insertToTemp(String Nama,String Alamat, String Barang_Sewa,int Harga, int Qty ,Connection conn,Statement s) throws SQLException{
        int sum = Harga*Qty;
        
        try {
        String sql = "INSERT INTO detail_report (Date,Nama,Alamat,Barang_Sewa,Qty,Harga,Sum) VALUES (?,?,?,?,?,?,?)";
        Timestamp Date = new Timestamp(new java.util.Date().getTime());
            try (java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setTimestamp(1, Date);
                pst.setString(2, Nama);
                pst.setString(3, Alamat);
                pst.setString(4, Barang_Sewa);
                pst.setInt(5, Qty);
                pst.setInt(6, Harga);
                pst.setInt(7, sum);
                pst.execute();
            }
        } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
        }
        return sum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMin1 = new javax.swing.JButton();
        btnPlus1 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        btnMin2 = new javax.swing.JButton();
        btnPlus2 = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        btnMin3 = new javax.swing.JButton();
        btnPlus3 = new javax.swing.JButton();
        txt3 = new javax.swing.JTextField();
        btnMin4 = new javax.swing.JButton();
        btnPlus4 = new javax.swing.JButton();
        txt4 = new javax.swing.JTextField();
        Btnmin5 = new javax.swing.JButton();
        btnPlus5 = new javax.swing.JButton();
        txt5 = new javax.swing.JTextField();
        btnMin6 = new javax.swing.JButton();
        btnPlus6 = new javax.swing.JButton();
        txt6 = new javax.swing.JTextField();
        btnMin7 = new javax.swing.JButton();
        btnPlus7 = new javax.swing.JButton();
        txt7 = new javax.swing.JTextField();
        sewa = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(788, 662));

        jPanel1.setPreferredSize(new java.awt.Dimension(768, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/next.png"))); // NOI18N
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/x 1.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        btnMin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/-.png"))); // NOI18N
        btnMin1.setBorder(null);
        btnMin1.setBorderPainted(false);
        btnMin1.setContentAreaFilled(false);
        btnMin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        btnPlus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/+.png"))); // NOI18N
        btnPlus1.setBorder(null);
        btnPlus1.setBorderPainted(false);
        btnPlus1.setContentAreaFilled(false);
        btnPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        txt1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("0");
        txt1.setBorder(null);
        txt1.setOpaque(false);
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 60, 30));

        btnMin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/-.png"))); // NOI18N
        btnMin2.setBorder(null);
        btnMin2.setBorderPainted(false);
        btnMin2.setContentAreaFilled(false);
        btnMin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMin2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        btnPlus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/+.png"))); // NOI18N
        btnPlus2.setBorder(null);
        btnPlus2.setBorderPainted(false);
        btnPlus2.setContentAreaFilled(false);
        btnPlus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));

        txt2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setText("0");
        txt2.setBorder(null);
        txt2.setOpaque(false);
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 60, 30));

        btnMin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/-.png"))); // NOI18N
        btnMin3.setBorder(null);
        btnMin3.setBorderPainted(false);
        btnMin3.setContentAreaFilled(false);
        btnMin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMin3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        btnPlus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/+.png"))); // NOI18N
        btnPlus3.setBorder(null);
        btnPlus3.setBorderPainted(false);
        btnPlus3.setContentAreaFilled(false);
        btnPlus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        txt3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt3.setText("0");
        txt3.setBorder(null);
        txt3.setOpaque(false);
        jPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 60, 30));

        btnMin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/-.png"))); // NOI18N
        btnMin4.setBorder(null);
        btnMin4.setBorderPainted(false);
        btnMin4.setContentAreaFilled(false);
        btnMin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMin4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        btnPlus4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/+.png"))); // NOI18N
        btnPlus4.setBorder(null);
        btnPlus4.setBorderPainted(false);
        btnPlus4.setContentAreaFilled(false);
        btnPlus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        txt4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt4.setText("0");
        txt4.setBorder(null);
        txt4.setOpaque(false);
        jPanel1.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 60, 30));

        Btnmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/-.png"))); // NOI18N
        Btnmin5.setBorder(null);
        Btnmin5.setBorderPainted(false);
        Btnmin5.setContentAreaFilled(false);
        Btnmin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnmin5ActionPerformed(evt);
            }
        });
        jPanel1.add(Btnmin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        btnPlus5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/+.png"))); // NOI18N
        btnPlus5.setBorder(null);
        btnPlus5.setBorderPainted(false);
        btnPlus5.setContentAreaFilled(false);
        btnPlus5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        txt5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5.setText("0");
        txt5.setBorder(null);
        txt5.setOpaque(false);
        jPanel1.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 60, 30));

        btnMin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/-.png"))); // NOI18N
        btnMin6.setBorder(null);
        btnMin6.setBorderPainted(false);
        btnMin6.setContentAreaFilled(false);
        btnMin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMin6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        btnPlus6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/+.png"))); // NOI18N
        btnPlus6.setBorder(null);
        btnPlus6.setBorderPainted(false);
        btnPlus6.setContentAreaFilled(false);
        btnPlus6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        txt6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt6.setText("0");
        txt6.setBorder(null);
        txt6.setOpaque(false);
        jPanel1.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 60, 30));

        btnMin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/-.png"))); // NOI18N
        btnMin7.setBorder(null);
        btnMin7.setBorderPainted(false);
        btnMin7.setContentAreaFilled(false);
        btnMin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMin7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        btnPlus7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/+.png"))); // NOI18N
        btnPlus7.setBorder(null);
        btnPlus7.setBorderPainted(false);
        btnPlus7.setContentAreaFilled(false);
        btnPlus7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, -1, -1));

        txt7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt7.setText("0");
        txt7.setBorder(null);
        txt7.setOpaque(false);
        jPanel1.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 60, 30));

        sewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sewaoutdoor/OOP ABET/Sewa.png"))); // NOI18N
        sewa.setText("0");
        jPanel1.add(sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(28, 101, 110));
        txtNama.setForeground(new java.awt.Color(28, 101, 110));
        txtNama.setBorder(null);
        txtNama.setOpaque(false);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        txtAlamat.setEditable(false);
        txtAlamat.setBackground(new java.awt.Color(28, 101, 110));
        txtAlamat.setForeground(new java.awt.Color(28, 101, 110));
        txtAlamat.setBorder(null);
        txtAlamat.setOpaque(false);
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMin1ActionPerformed
        // TODO add your handling code here:
         String strVa = txt1.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txt1.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Harus Lebih Dari 0" );
        }
    }//GEN-LAST:event_btnMin1ActionPerformed

    private void btnPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus1ActionPerformed
        // TODO add your handling code here:
        String strva = txt1.getText();
        int value = Integer.parseInt(strva);
            value ++;
        String result = String.valueOf(value);
        txt1.setText(result);
        
        
    }//GEN-LAST:event_btnPlus1ActionPerformed

    private void btnMin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMin2ActionPerformed
        // TODO add your handling code here:
        String strVa = txt2.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txt2.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Harus Lebih Dari 0" );
        }
    }//GEN-LAST:event_btnMin2ActionPerformed

    private void btnPlus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus2ActionPerformed
        // TODO add your handling code here:
        String strva = txt2.getText();
        int value = Integer.parseInt(strva);
            value ++;
        String result = String.valueOf(value);
        txt2.setText(result);
    }//GEN-LAST:event_btnPlus2ActionPerformed

    private void btnPlus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus3ActionPerformed
        // TODO add your handling code here:
        String strva = txt3.getText();
        int value = Integer.parseInt(strva);
            value ++;
        String result = String.valueOf(value);
        txt3.setText(result);
    }//GEN-LAST:event_btnPlus3ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        // Nilai Item
            String strVa1 = txt1.getText();
            int value1 = Integer.parseInt(strVa1);
            String strVa2 = txt2.getText();
            int value2 = Integer.parseInt(strVa2);
            String strVa3 = txt3.getText();
            int value3 = Integer.parseInt(strVa3);
            String strVa4 = txt4.getText();
            int value4 = Integer.parseInt(strVa4);
            String strVa5 = txt5.getText();
            int value5 = Integer.parseInt(strVa5);
            String strVa6 = txt6.getText();
            int value6 = Integer.parseInt(strVa6);
            String strVa7 = txt7.getText();
            int value7 = Integer.parseInt(strVa7);
            
            //Harga Item
            int price1 = 35000;
            int price2 = 45500;
            int price3 = 10000;
            int price4 = 10000;
            int price5 = 15000;
            int price6 = 10000;
            int price7 = 10000;
            
            
            int total = 0;
             if (value1>0||value2>0||value3>0||value4>0||value5>0||value6>0||value7>0) {
                try {
                    Connection conn = ConnectDB.getConnection();
                    Statement s = conn.createStatement();
                    TampilanDepan tampilanDepan = new TampilanDepan();
                    String nama = txtNama.getText();
                    System.out.println(nama);
                    String alamat = txtAlamat.getText();
                    System.out.println(alamat);
                    if(value1>0){
                        String barang = "Tenda 3-4";
                        int x =insertToTemp(nama,alamat,barang,price1,value1,conn,s);
                        total += x;
                    }
                    
                    if(value2>0){
                        String barang = "Tenda 4-5";
                        int x =insertToTemp(nama,alamat,barang, price2, value2 ,conn,s);
                        total += x;
                    }
                    
                    
                    if(value3>0){
                        String barang = "Sleeping Bag";
                        int x =insertToTemp(nama,alamat,barang, price3, value3 ,conn,s);
                        total += x;
                    }
                    
                    if(value4>0){
                        String barang = "Kompor";
                        int x =insertToTemp(nama,alamat,barang, price4, value4 ,conn,s);
                        total += x;
                    }
                    
                    if(value5>0){
                        String barang = "Cooking set";
                        int x =insertToTemp(nama,alamat,barang, price5, value5 ,conn,s);
                        total += x;
                    }
                    
                    if(value6>0){
                        String barang = "Gas";
                        int x =insertToTemp(nama,alamat,barang, price6, value6 ,conn,s);
                        total += x;
                    }
                    
                    if(value7>0){
                        String barang = "Hammock";
                        int x =insertToTemp(nama,alamat,barang, price7, value7 ,conn,s);
                        total += x;
                    }
                    
                    detail newDetail=new detail();
                    newDetail.setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(Sewa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "You haven't buy anyone yet" );
            }
        
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnMin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMin3ActionPerformed
        // TODO add your handling code here:
        String strVa = txt3.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txt3.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Harus Lebih Dari 0" );
        }
    }//GEN-LAST:event_btnMin3ActionPerformed

    private void btnMin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMin4ActionPerformed
        // TODO add your handling code here:
        String strVa = txt4.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txt4.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Harus Lebih Dari 0" );
        }
    }//GEN-LAST:event_btnMin4ActionPerformed

    private void Btnmin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnmin5ActionPerformed
        // TODO add your handling code here:
        String strVa = txt5.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txt5.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Harus Lebih Dari 0" );
        }
    }//GEN-LAST:event_Btnmin5ActionPerformed

    private void btnMin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMin6ActionPerformed
        // TODO add your handling code here:
        String strVa = txt6.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txt6.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Harus Lebih Dari 0" );
        }
    }//GEN-LAST:event_btnMin6ActionPerformed

    private void btnMin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMin7ActionPerformed
        // TODO add your handling code here:
        String strVa = txt7.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txt7.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Harus Lebih Dari 0" );
        }
    }//GEN-LAST:event_btnMin7ActionPerformed

    private void btnPlus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus4ActionPerformed
        // TODO add your handling code here:
        String strva = txt4.getText();
        int value = Integer.parseInt(strva);
            value ++;
        String result = String.valueOf(value);
        txt4.setText(result);
    }//GEN-LAST:event_btnPlus4ActionPerformed

    private void btnPlus5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus5ActionPerformed
        // TODO add your handling code here:
        String strva = txt5.getText();
        int value = Integer.parseInt(strva);
            value ++;
        String result = String.valueOf(value);
        txt5.setText(result);
    }//GEN-LAST:event_btnPlus5ActionPerformed

    private void btnPlus6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus6ActionPerformed
        // TODO add your handling code here:
        String strva = txt6.getText();
        int value = Integer.parseInt(strva);
            value ++;
        String result = String.valueOf(value);
        txt6.setText(result);
    }//GEN-LAST:event_btnPlus6ActionPerformed

    private void btnPlus7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus7ActionPerformed
        // TODO add your handling code here:
        String strva = txt7.getText();
        int value = Integer.parseInt(strva);
            value ++;
        String result = String.valueOf(value);
        txt7.setText(result);
    }//GEN-LAST:event_btnPlus7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnmin5;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMin1;
    private javax.swing.JButton btnMin2;
    private javax.swing.JButton btnMin3;
    private javax.swing.JButton btnMin4;
    private javax.swing.JButton btnMin6;
    private javax.swing.JButton btnMin7;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlus1;
    private javax.swing.JButton btnPlus2;
    private javax.swing.JButton btnPlus3;
    private javax.swing.JButton btnPlus4;
    private javax.swing.JButton btnPlus5;
    private javax.swing.JButton btnPlus6;
    private javax.swing.JButton btnPlus7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sewa;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    public static javax.swing.JTextField txtAlamat;
    public static javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

   
}
